// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ucred_ff
Rcpp::List ucred_ff(const char * data, const char * query, int qlength);
RcppExport SEXP rucrdtw_ucred_ff(SEXP dataSEXP, SEXP querySEXP, SEXP qlengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const char * >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type qlength(qlengthSEXP);
    rcpp_result_gen = Rcpp::wrap(ucred_ff(data, query, qlength));
    return rcpp_result_gen;
END_RCPP
}
// ucred_fv
Rcpp::List ucred_fv(const char * data, Rcpp::NumericVector query, int qlength);
RcppExport SEXP rucrdtw_ucred_fv(SEXP dataSEXP, SEXP querySEXP, SEXP qlengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type qlength(qlengthSEXP);
    rcpp_result_gen = Rcpp::wrap(ucred_fv(data, query, qlength));
    return rcpp_result_gen;
END_RCPP
}
// ucred_vv
Rcpp::List ucred_vv(Rcpp::NumericVector data, Rcpp::NumericVector query, int qlength);
RcppExport SEXP rucrdtw_ucred_vv(SEXP dataSEXP, SEXP querySEXP, SEXP qlengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type qlength(qlengthSEXP);
    rcpp_result_gen = Rcpp::wrap(ucred_vv(data, query, qlength));
    return rcpp_result_gen;
END_RCPP
}
// ucrdtw_ff
Rcpp::List ucrdtw_ff(const char * data, const char * query, int qlength, double dtwwindow);
RcppExport SEXP rucrdtw_ucrdtw_ff(SEXP dataSEXP, SEXP querySEXP, SEXP qlengthSEXP, SEXP dtwwindowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const char * >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type qlength(qlengthSEXP);
    Rcpp::traits::input_parameter< double >::type dtwwindow(dtwwindowSEXP);
    rcpp_result_gen = Rcpp::wrap(ucrdtw_ff(data, query, qlength, dtwwindow));
    return rcpp_result_gen;
END_RCPP
}
// ucrdtw_fv
Rcpp::List ucrdtw_fv(const char * data, Rcpp::NumericVector query, int qlength, double dtwwindow);
RcppExport SEXP rucrdtw_ucrdtw_fv(SEXP dataSEXP, SEXP querySEXP, SEXP qlengthSEXP, SEXP dtwwindowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type qlength(qlengthSEXP);
    Rcpp::traits::input_parameter< double >::type dtwwindow(dtwwindowSEXP);
    rcpp_result_gen = Rcpp::wrap(ucrdtw_fv(data, query, qlength, dtwwindow));
    return rcpp_result_gen;
END_RCPP
}
// ucrdtw_vv
Rcpp::List ucrdtw_vv(Rcpp::NumericVector data, Rcpp::NumericVector query, int qlength, double dtwwindow, int epoch, bool skip);
RcppExport SEXP rucrdtw_ucrdtw_vv(SEXP dataSEXP, SEXP querySEXP, SEXP qlengthSEXP, SEXP dtwwindowSEXP, SEXP epochSEXP, SEXP skipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type qlength(qlengthSEXP);
    Rcpp::traits::input_parameter< double >::type dtwwindow(dtwwindowSEXP);
    Rcpp::traits::input_parameter< int >::type epoch(epochSEXP);
    Rcpp::traits::input_parameter< bool >::type skip(skipSEXP);
    rcpp_result_gen = Rcpp::wrap(ucrdtw_vv(data, query, qlength, dtwwindow, epoch, skip));
    return rcpp_result_gen;
END_RCPP
}
