// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ucrdtw_ff
Rcpp::List ucrdtw_ff(const char * data, const char * query, int qlength, double dtwwindow);
RcppExport SEXP rucrdtw_ucrdtw_ff(SEXP dataSEXP, SEXP querySEXP, SEXP qlengthSEXP, SEXP dtwwindowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const char * >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type qlength(qlengthSEXP);
    Rcpp::traits::input_parameter< double >::type dtwwindow(dtwwindowSEXP);
    rcpp_result_gen = Rcpp::wrap(ucrdtw_ff(data, query, qlength, dtwwindow));
    return rcpp_result_gen;
END_RCPP
}
