# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' UCR ED Algorithm file-file method
#'
#' This implementation is very close to the UCR Suite command line utility, in that it takes files as inputs for both query and data
#'
#' @name ucred_ff
#' @param data char path to data file
#' @param query char path to query file
#' @param qlength int length of query (n data points)
#' @useDynLib rucrdtw
#' @importFrom Rcpp sourceCpp
#' @export
ucred_ff <- function(data, query, qlength) {
    .Call('rucrdtw_ucred_ff', PACKAGE = 'rucrdtw', data, query, qlength)
}

#' UCR ED Algorithm file-vector method
#'
#' This implementation of the UCR Suite command line utility, takes a data file as input and an R numeric vector for the query.
#'
#' @name ucred_fv
#' @param data char path to data file
#' @param query numeric vector containing query
#' @param qlength int length of query (n data points)
#' @useDynLib rucrdtw
#' @importFrom Rcpp sourceCpp
#' @export
ucred_fv <- function(data, query, qlength) {
    .Call('rucrdtw_ucred_fv', PACKAGE = 'rucrdtw', data, query, qlength)
}

#' UCR ED Algorithm vector-vector method
#'
#' This implementation of the UCR Suite Euclidean Distance command line utility takes an R numeric vector as data input and an R numeric vector for the query.
#'
#' @name ucred_vv
#' @param data numeric vector containing data
#' @param query numeric vector containing query
#' @param qlength int length of query (n data points)
#' @useDynLib rucrdtw
#' @importFrom Rcpp sourceCpp
#' @export
ucred_vv <- function(data, query, qlength) {
    .Call('rucrdtw_ucred_vv', PACKAGE = 'rucrdtw', data, query, qlength)
}

#' UCR DTW Algorithm file-file method
#'
#' This implementation is very close to the UCR Suite command line utility, in that it takes files as inputs for both query and data
#'
#' @name ucrdtw_ff
#' @param data char path to data file
#' @param query char path to query file
#' @param qlength int length of query (n data points)
#' @param dtwwindow double warping window size (as a proportion of query length)
#' @useDynLib rucrdtw
#' @importFrom Rcpp sourceCpp
#' @export
ucrdtw_ff <- function(data, query, qlength, dtwwindow) {
    .Call('rucrdtw_ucrdtw_ff', PACKAGE = 'rucrdtw', data, query, qlength, dtwwindow)
}

#' UCR DTW Algorithm file-vector method
#'
#' This implementation of the UCR Suite command line utility, takes a data file as input and an R numeric vector for the query
#'
#' @name ucrdtw_fv
#' @param data char path to data file
#' @param query numeric vector containing the query
#' @param qlength int length of query (n data points)
#' @param dtwwindow double warping window size (as a proportion of query length)
#' @useDynLib rucrdtw
#' @importFrom Rcpp sourceCpp
#' @export
ucrdtw_fv <- function(data, query, qlength, dtwwindow) {
    .Call('rucrdtw_ucrdtw_fv', PACKAGE = 'rucrdtw', data, query, qlength, dtwwindow)
}

#' UCR DTW Algorithm vector-vector method
#'
#' This implementation of the UCR Suite command line utility, takes an R numeric vector as data input and an R numeric vector for the query
#'
#' @name ucrdtw_vv
#' @param data numeric vector containing data
#' @param query numeric vector containing the query
#' @param qlength int length of query (n data points)
#' @param dtwwindow double warping window size (as a proportion of query length)
#' @param epoch int defaults to 1e5, should be \eqn{\le} 1e6. This is the size of the data chunk that is processed at once. All cumulative values in the algorithm will be restarted after \code{epoch} iterations to reduce floating point errors in these values.
#' @param skip bool defaults to FALSE. If TRUE bound calculations and if necessary, distance calculations, are only performed on non-overlapping segments of the data (i.e. multiples of \code{qlength}). This is useful if \code{data} is a set of multiple reference time series, each of length \code{qlength}. The location returned when skipping is the index of the subsequence.
#' @useDynLib rucrdtw
#' @importFrom Rcpp sourceCpp
#' @export
ucrdtw_vv <- function(data, query, qlength, dtwwindow, epoch = 100000L, skip = FALSE) {
    .Call('rucrdtw_ucrdtw_vv', PACKAGE = 'rucrdtw', data, query, qlength, dtwwindow, epoch, skip)
}

