# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' UCR DTW Algorithm file-file method
#'
#' This implementation is very close to the UCR Suite command line utility, in that it takes files as inputs for both query and data
#'
#' @name ucrdtw_ff
#' @param data char path to data file
#' @param query char path to query file
#' @param qlength int length of query (n data points)
#' @param dtwwindow double warping window size (as a proportion of query length)
#' @useDynLib rucrdtw
#' @importFrom Rcpp sourceCpp
#' @export
ucrdtw_ff <- function(data, query, qlength, dtwwindow) {
    .Call('rucrdtw_ucrdtw_ff', PACKAGE = 'rucrdtw', data, query, qlength, dtwwindow)
}

#' UCR DTW Algorithm file-vector method
#'
#' This implementation of the UCR Suite command line utility, takes a data file as input and an R numeric vector for the query
#'
#' @name ucrdtw_fv
#' @param data char path to data file
#' @param query numeric vector containing the query
#' @param qlength int length of query (n data points)
#' @param dtwwindow double warping window size (as a proportion of query length)
#' @useDynLib rucrdtw
#' @importFrom Rcpp sourceCpp
#' @export
ucrdtw_fv <- function(data, query, qlength, dtwwindow) {
    .Call('rucrdtw_ucrdtw_fv', PACKAGE = 'rucrdtw', data, query, qlength, dtwwindow)
}

#' UCR DTW Algorithm vector-vector method
#'
#' This implementation of the UCR Suite command line utility, takes an R numeric vector as data input and an R numeric vector for the query
#'
#' @name ucrdtw_vv
#' @param datav numeric vector containing data
#' @param query numeric vector containing the query
#' @param qlength int length of query (n data points)
#' @param dtwwindow double warping window size (as a proportion of query length)
#' @useDynLib rucrdtw
#' @importFrom Rcpp sourceCpp
#' @export
ucrdtw_vv <- function(data, query, qlength, dtwwindow) {
    .Call('rucrdtw_ucrdtw_vv', PACKAGE = 'rucrdtw', data, query, qlength, dtwwindow)
}

